version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: wirehead/wirehead-charts
          command: wget -O - https://raw.githubusercontent.com/wirehead/helm-github-pages/master/publish.sh | sh