{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semanticmediawiki.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "semanticmediawiki.name" . }}
    helm.sh/chart: {{ include "semanticmediawiki.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.wiki.secretKey }}
  secret-key: {{ .Values.wiki.secretKey | b64enc | quote }}
  {{ else }}
  secret-key: {{ randNumeric 64 | b64enc | quote }}
  {{ end }}
  {{ if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{ end }}
{{- end }}
